name: task
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  dio: ^5.3.3

  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^3.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
